name: Build APK Rubik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libffi-dev libgdbm-dev bluez libasound2-dev bsdmainutils

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer==1.5.0 cython==0.29.36 virtualenv

     - name: Build APK with Buildozer
      run: |
        # Lệnh thần thánh tự động đồng ý tất cả điều khoản bản quyền của Google Android SDK
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Chạy buildozer sau khi đã xong bản quyền
        buildozer android debug
      env:
        ACCEPT_FDL_LICENSE: "y"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rubik-APK
        path: bin/*.apk
